# Dockerfile.local
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY octoprint-api.py .

ENV ENABLE_OPCUA=false

CMD ["python", "octoprint-api.py"]